---
- name: Deploy Student Enrollment App
  hosts: webserver
  # become: yes  <-- DELETE OR COMMENT OUT THIS LINE
  vars:
    docker_image: jerral/student-enrollment-app:latest
    container_name: enrollment_app_container
    graphite_host: 172.17.0.1 

  tasks:
    # We don't need these tasks anymore because Docker is already installed
    # and running on the host, which is all that matters. Comment them out.
    # - name: Ensure Docker is installed (apt)
    #   apt:
    #     name: docker.io
    #     state: present
    #     update_cache: yes

    # - name: Ensure Docker Python library is installed
    #   pip:
    #     name: docker
    #     state: present

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop and remove the existing container if it exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Start the new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"
        env:
          GRAPHITE_HOST: "{{ graphite_host }}"
